<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../receivePO.wsdl"/>
      <rootElement name="PurchaseOrder" namespace="http://www.example.org/ns/porder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../WritePOFileSrv.wsdl"/>
      <rootElement name="order" namespace="http://www.example.org/ns/intorder"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU DEC 07 03:03:48 PST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:inp1="http://www.example.org/ns/porder"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/POApp/POProcessing/WritePOFileSrv"
                xmlns:tns="http://oracle.com/sca/soapservice/POApp/POProcessing/receivePO"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:imp1="http://www.example.org/ns/intorder"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl inp1 wsdl tns xsd plt ns0 jca imp1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:order>
      <imp1:customerId>
        <xsl:value-of select="/inp1:PurchaseOrder/inp1:custID"/>
      </imp1:customerId>
      <imp1:orderId>
        <xsl:value-of select="/inp1:PurchaseOrder/inp1:ID"/>
      </imp1:orderId>
      <imp1:payMethod>
        <xsl:value-of select="/inp1:PurchaseOrder/inp1:payOption"/>
      </imp1:payMethod>
      <imp1:shipMethod>
        <xsl:value-of select="/inp1:PurchaseOrder/inp1:shipChoice"/>
      </imp1:shipMethod>
      <imp1:status>
        <xsl:value-of select="/inp1:PurchaseOrder/inp1:status"/>
      </imp1:status>
      <imp1:creditCard>
        <imp1:cardType>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:ccType"/>
        </imp1:cardType>
        <imp1:cardNumber>
          <xsl:value-of select="/inp1:PurchaseOrder/inp1:ccNumber"/>
        </imp1:cardNumber>
      </imp1:creditCard>
      <imp1:items>
        <imp1:inStock>
          <xsl:text disable-output-escaping="no">true</xsl:text>
        </imp1:inStock>
        <xsl:for-each select="/inp1:PurchaseOrder/inp1:items/inp1:item">
          <imp1:item>
            <imp1:prodId>
              <xsl:value-of select="inp1:productId"/>
            </imp1:prodId>
            <imp1:prodName>
              <xsl:value-of select="inp1:productName"/>
            </imp1:prodName>
            <imp1:price>
              <xsl:value-of select="inp1:price"/>
            </imp1:price>
            <imp1:qty>
              <xsl:value-of select="inp1:quantity"/>
            </imp1:qty>
            <imp1:itemTotal>
              <xsl:value-of select="inp1:quantity * inp1:price"/>
            </imp1:itemTotal>
          </imp1:item>
        </xsl:for-each>
      </imp1:items>
    </imp1:order>
  </xsl:template>
</xsl:stylesheet>
