<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../ApproveCCorder.wsdl"/>
      <rootElement name="order" namespace="http://www.example.org/ns/intorder"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../Fulfillment.wsdl"/>
      <rootElement name="FulFillmentRequest" namespace="http://www.example.org/ns/fulfillment"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU DEC 07 04:13:17 PST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://xmlns.oracle.com/POApp/POProcessing/Fulfillment"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns1="http://www.example.org/ns/intorder"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns0="http://www.example.org/ns/fulfillment"
                xmlns:client="http://xmlns.oracle.com/POApp/POProcessing/ApproveCCorder"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl wsdl plnk ns1 xsd client ns2 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns0:FulFillmentRequest>
      <ns1:customerId>
        <xsl:value-of select="/ns1:order/ns1:customerId"/>
      </ns1:customerId>
      <ns1:orderId>
        <xsl:value-of select="/ns1:order/ns1:orderId"/>
      </ns1:orderId>
      <ns1:payMethod>
        <xsl:value-of select="/ns1:order/ns1:payMethod"/>
      </ns1:payMethod>
      <ns1:shipMethod>
        <xsl:value-of select="/ns1:order/ns1:shipMethod"/>
      </ns1:shipMethod>
      <ns1:orderTotal>
        <xsl:value-of select="/ns1:order/ns1:orderTotal"/>
      </ns1:orderTotal>
      <ns1:status>
        <xsl:value-of select="/ns1:order/ns1:status"/>
      </ns1:status>
      <ns1:creditCard>
        <ns1:cardType>
          <xsl:value-of select="/ns1:order/ns1:creditCard/ns1:cardType"/>
        </ns1:cardType>
        <ns1:cardNumber>
          <xsl:value-of select="/ns1:order/ns1:creditCard/ns1:cardNumber"/>
        </ns1:cardNumber>
      </ns1:creditCard>
      <ns1:items>
        <ns1:inStock>
          <xsl:value-of select="/ns1:order/ns1:items/ns1:inStock"/>
        </ns1:inStock>
        <xsl:for-each select="/ns1:order/ns1:items/ns1:item">
          <ns1:item>
            <ns1:prodId>
              <xsl:value-of select="ns1:prodId"/>
            </ns1:prodId>
            <ns1:prodName>
              <xsl:value-of select="ns1:prodName"/>
            </ns1:prodName>
            <ns1:price>
              <xsl:value-of select="ns1:price"/>
            </ns1:price>
            <ns1:qty>
              <xsl:value-of select="ns1:qty"/>
            </ns1:qty>
            <ns1:itemTotal>
              <xsl:value-of select="ns1:itemTotal"/>
            </ns1:itemTotal>
          </ns1:item>
        </xsl:for-each>
      </ns1:items>
    </ns0:FulFillmentRequest>
  </xsl:template>
</xsl:stylesheet>
