<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../consume_queue.wsdl"/>
      <rootElement name="ShippingRequest" namespace="http://www.example.org/ns/fulfillment"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../writeQueue.wsdl"/>
      <rootElement name="ShippingRequest" namespace="http://www.example.org/ns/fulfillment"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON DEC 11 08:30:28 PST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/POApp/queueReader/writeQueue"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/POApp/queueReader/consume_queue"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.example.org/ns/intorder"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:imp1="http://www.example.org/ns/fulfillment"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl pc plt wsdl jca tns ns0 xsd imp1 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <imp1:ShippingRequest>
      <imp1:orderId>
        <xsl:value-of select="/imp1:ShippingRequest/imp1:orderId"/>
      </imp1:orderId>
      <imp1:custName>
        <xsl:value-of select="/imp1:ShippingRequest/imp1:custName"/>
      </imp1:custName>
      <imp1:shippingAddress>
        <imp1:street>
          <xsl:value-of select="/imp1:ShippingRequest/imp1:shippingAddress/imp1:street"/>
        </imp1:street>
        <imp1:city>
          <xsl:value-of select="/imp1:ShippingRequest/imp1:shippingAddress/imp1:city"/>
        </imp1:city>
        <imp1:state>
          <xsl:value-of select="/imp1:ShippingRequest/imp1:shippingAddress/imp1:state"/>
        </imp1:state>
        <imp1:zip>
          <xsl:value-of select="/imp1:ShippingRequest/imp1:shippingAddress/imp1:zip"/>
        </imp1:zip>
        <imp1:country>
          <xsl:value-of select="/imp1:ShippingRequest/imp1:shippingAddress/imp1:country"/>
        </imp1:country>
      </imp1:shippingAddress>
    </imp1:ShippingRequest>
  </xsl:template>
</xsl:stylesheet>
