<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../customerAdpater.wsdl"/>
      <rootElement name="CustomersCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerAdpater"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../customerService.wsdl"/>
      <rootElement name="CustomerResponse" namespace="http://www.example.org"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU DEC 14 09:38:22 PST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:inp1="http://www.example.org"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/customerAdpater"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/POApp/customerService/customerAdpater"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns0="http://oracle.com/sca/soapservice/POApp/customerService/customerService"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl top tns plt wsdl xsd inp1 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <inp1:CustomerResponse>
      <inp1:id>
        <inp1:custID>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:custId"/>
        </inp1:custID>
      </inp1:id>
      <inp1:customer>
        <inp1:firstName>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:firstName"/>
        </inp1:firstName>
        <inp1:lastName>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:lastName"/>
        </inp1:lastName>
        <inp1:userName>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:username"/>
        </inp1:userName>
        <inp1:email>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:email"/>
        </inp1:email>
        <inp1:status>
          <xsl:value-of select="/top:CustomersCollection/top:Customers/top:status"/>
        </inp1:status>
      </inp1:customer>
      <xsl:for-each select="/top:CustomersCollection/top:Customers/top:addressCollection/top:Address">
        <inp1:shippingAddress>
          <inp1:street>
            <xsl:value-of select="top:street"/>
          </inp1:street>
          <inp1:city>
            <xsl:value-of select="top:city"/>
          </inp1:city>
          <inp1:state>
            <xsl:value-of select="top:state"/>
          </inp1:state>
          <inp1:zip>
            <xsl:value-of select="top:zip"/>
          </inp1:zip>
          <inp1:country>
            <xsl:value-of select="top:country"/>
          </inp1:country>
        </inp1:shippingAddress>
      </xsl:for-each>
    </inp1:CustomerResponse>
  </xsl:template>
</xsl:stylesheet>
